---
# tasks file for docker
- name: get needed facts
  ansible.builtin.setup:
    gather_subset:
      - min

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: install docker
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present
  notify: restart docker

- name: start and enable docker at boot
  ansible.builtin.service:
    name: docker
    state: "{{ docker_service|default(started) }}"
    enabled: "{{ docker_service_enabled|default(true) }}"

- name: flush handlers
  meta: flush_handlers

- name: create local network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    enable_ipv6: "{{ docker_ipv6|default(no) }}"
    internal: yes
    ipam_config:
      - subnet: "{{ docker_ip4_net }}"



- include_tasks: docker-users.yml
  when: docker_users | length > 0
