---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
    - name: wait for systemd
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgt == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  tasks:
    - name: install docker
      include_role:
        name: joshuaejs.docker
